
import type { Metadata } from "next";
import "./globals.css";
import { LayoutWrapper } from "@/components/Wrapper/LayoutWrapper";
import { Noto_Sans } from "next/font/google";
import { LanguageProvider } from "@/context/LanguageContext";

const notoSans = Noto_Sans({
  subsets: ["latin"], 
  variable: "--font-noto", 
});

export const metadata: Metadata = {
  title: "XPARTEX",
  description: "Generated by XPARTEX",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={notoSans.className}>
      <body >
        <LanguageProvider>
          <LayoutWrapper>{children}</LayoutWrapper>
        </LanguageProvider>
      </body>
    </html>
  );
}
